DoctorChamberAppointmentSystem/Controllers/AdminController.cs
using DoctorChamberAppointmentMangementSystem.Models.Entity;
using DoctorChamberAppointmentMangementSystem.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoctorChamberAppointmentMangementSystem.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/
        private readonly DoctorAppointmentDbContext _dbContext = new DoctorAppointmentDbContext();
        public ActionResult Index(string roleName)
        {
            var a = ViewBag.RoleName;
          ViewBag.RoleName = Session["Role"].ToString();
             return View();
        }
       
        public ActionResult PatientList()
        {
           var patient= _dbContext.Patient.ToList();

           return View(patient);
        }

        public ActionResult DoctorList()
        {
            var doctor = _dbContext.Doctors.ToList();

            return View(doctor);
        }
        public ActionResult AppointmentList()
   {
          

            DateTime nowDate = Convert.ToDateTime(DateTime.Today.Date.ToShortDateString());
            int day = 1;

            List<AppointmentList> appoints=new List<AppointmentList>();
          for(int i=0;i<1;i++)
          {
              TimeList obj2 = new TimeList();
              nowDate = nowDate.AddDays(day);
              obj2.Year = DateTime.Now.Year.ToString();
              obj2.Day = nowDate.ToString("dddd");
              obj2.Date = nowDate.ToString("MMMM dd");
              DateTime date = Convert.ToDateTime(obj2.Date);
              var patient = _dbContext.Patient.ToList();
              var doctors = _dbContext.Doctors.ToList();
              var appoint = _dbContext.Appointments.Where(d => d.Date == date).ToList();

              List<Patient> patientList = patient;
              List<Doctor> doctorList = doctors;
                    appoints  = (from a in appoint
                                                join p in patientList on a.PatientId equals p.Id
                                                join d in doctorList on p.DoctorId equals d.DoctorId
                                                select new AppointmentList
                                                {
                                                    Id=a.AppointmentId,
                                                    PatientName = p.PatientName,
                                                    AppointmentSerialNo = p.AppointmentSerialNo,
                                                    Time = a.Time,
                                                    PhoneNumber = p.PhoneNumber,
                                                    DoctorName = d.Name,
                                                    DoctorLocation = d.ChamberOfLocation,
                                                    DoctorPhoneNo = d.PhoneNo

                                                }).ToList();
                        }
                
         
                

            
           
            return View(appoints.ToList());
        }
        [HttpPost]
         public ActionResult Delete(int id)
        {
           Appointment appointDetails= _dbContext.Appointments.Find(id);
           _dbContext.Appointments.Remove(appointDetails);
           _dbContext.SaveChanges();
           return RedirectToAction("AppointmentList");


        }


    }
}

DoctorChamberAppointmentSystem/Controllers/DoctorController.cs
using DoctorChamberAppointmentMangementSystem.Models.Entity;
using DoctorChamberAppointmentMangementSystem.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DoctorChamberAppointmentMangementSystem.Controllers
{
    public class DoctorController : Controller
    {
        private readonly DoctorAppointmentDbContext _dbContext = new DoctorAppointmentDbContext();

        public ActionResult Welcome(string roleName)
        {
            var a = ViewBag.RoleName;
            ViewBag.RoleName = Session["Role"].ToString();
            return View();
        }
        public ActionResult Index()
        {
            ViewBag.RoleName = Session["Role"].ToString();
            return View();
        }
        [HttpPost]
        public ActionResult Index(DoctorVM aDoctor)
        {
            
            string fileName = Path.GetFileNameWithoutExtension( aDoctor.UploadOfFile.FileName);
            string extension = Path.GetExtension(aDoctor.UploadOfFile.FileName);
            if (fileName.Length> 96)
            {
               ViewBag.Message = "Please enter your photo";
            }
            else if (extension != ".jpeg" && extension != ".jpg" && extension != ".png" && extension != ".bmp")
            {
                ViewBag.Message = "Please Enter photo file Accepted by jpg,jpeg,png,bmp";
            }
            else if (aDoctor.UploadOfFile.ContentLength > 4000000)
            {
                ViewBag.Message = "maximum length ";
            }
            else
            {
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                aDoctor.PhotoPath = "~/Image/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
                aDoctor.UploadOfFile.SaveAs(fileName);
            }
         
            try
            {
             
                Doctor doctor = new Doctor()
                {
                    Name = aDoctor.Name,
                    Gender = aDoctor.Gender,
                    MedicalName  = aDoctor.MedicalName,
                    Department = aDoctor.Department,
                    Speciality = aDoctor.Speciality,
                    ChamberOfLocation = aDoctor.ChamberOfAddress,
                    UploadOfPhoto = aDoctor.PhotoPath,
                    PhoneNo = aDoctor.MobileNo,
                    Fees = aDoctor.Fees,
                    Email = aDoctor.Email,
                    BMDCRegNo=aDoctor.BMDCRegNo,
                     StartTime=Convert.ToString( aDoctor.StartTime)+""+aDoctor.StartAmPm,
                   EndTime= Convert.ToString(aDoctor.EndTime)+""+aDoctor.EndAmPm,
                    Description=aDoctor.Description,
                    InstitutionDegree=aDoctor.InstitutionOfDegree,
                    Degination=aDoctor.Degination



                };
                _dbContext.Doctors.Add(doctor);
                _dbContext.SaveChanges();
                ViewBag.Success = "Save Successfully";
                ModelState.Clear();
            }
            catch(Exception e)
            {
              ViewBag.Error=  e.Message;
            }
    

                
                

            return View();
        }
        public ActionResult Registration()
        {
            return View();
        }
        public ActionResult AppointmentList()
        {


            DateTime nowDate = Convert.ToDateTime(DateTime.Today.Date.ToShortDateString());
            int day = 1;

            List<AppointmentList> appoints = new List<AppointmentList>();
            for (int i = 0; i < 1; i++)
            {
                TimeList obj2 = new TimeList();
                nowDate = nowDate.AddDays(day);
                obj2.Year = DateTime.Now.Year.ToString();
                obj2.Day = nowDate.ToString("dddd");
                obj2.Date = nowDate.ToString("MMMM dd");
                DateTime date = Convert.ToDateTime(obj2.Date);
                var patient = _dbContext.Patient.ToList();
                var doctors = _dbContext.Doctors.ToList();
                var appoint = _dbContext.Appointments.Where(d => d.Date == date).ToList();

                List<Patient> patientList = patient;
                List<Doctor> doctorList = doctors;
                appoints = (from a in appoint
                            join p in patientList on a.PatientId equals p.Id
                            join d in doctorList on p.DoctorId equals d.DoctorId
                            select new AppointmentList
                            {
                                Id = a.AppointmentId,
                                PatientName = p.PatientName,
                                AppointmentSerialNo = p.AppointmentSerialNo,
                                Time = a.Time,
                                PhoneNumber = p.PhoneNumber,
                                DoctorName = d.Name,
                                DoctorLocation = d.ChamberOfLocation,
                                DoctorPhoneNo = d.PhoneNo

                            }).ToList();
            }






            return View(appoints.ToList());
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            Appointment appointDetails = _dbContext.Appointments.Find(id);
            _dbContext.Appointments.Remove(appointDetails);
            _dbContext.SaveChanges();
            return RedirectToAction("AppointmentList");


        }

    }
}

DoctorChamberAppointmentSystem/Views/Shared/AdminPartial.cshtml
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.0.0.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

<style>
    .table {
        margin-bottom: 0px;
    }

    table tr td {
        border-bottom: 1px solid #dddddd;
    }
</style>
<div class="container">

    <div class="panel-group">


        <div class="panel panel-primary">
            <div class="panel-heading">Admin</div>
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <td>
                            @Html.ActionLink("List of Patient", "PatientList", "Admin")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.ActionLink("List of Doctor", "DoctorList", "Admin")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.ActionLink("List of Appointment", "AppointmentList", "Admin")
                        </td>
                    </tr>

                </table>
            </div>
        </div>
    </div>
</div>

DoctorChamberAppointmentSystem/Views/Shared/DoctorPartial.cshtml
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.0.0.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

<style>
    .table {
        margin-bottom: 0px;
    }

    table tr td {
        border-bottom: 1px solid #dddddd;
    }
</style>
<div class="container">
    
    <div class="panel-group">
     

        <div class="panel panel-primary">
            <div class="panel-heading">Doctor</div>
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <td>
                            @Html.ActionLink("Personal Information", "Index", "Doctor")
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Html.ActionLink("List of Appointment", "AppointmentList", "Doctor")
                        </td>
                    </tr>
                
                </table>
            </div>
        </div>
    </div>
</div>

DoctorChamberAppointmentSystem/Views/Shared/PatientPartial.cshtml
<h1>Patient</h1>

DoctorChamberAppointmentSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

</head>
<body >
    
       
            <nav class="navbar navbar-expand-lg navbar-light bg-light" >
                <a class="navbar-brand" href="/Patient/Department"><img  src="~/Image/logo.png" style="width:50%;" /></a>


                <div class=" navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item active">

                        </li>
                        <li class="nav-item">

                        </li>
                        <li class="nav-item">

                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">


                        <a href="/User/Index" class="btn btn-outline-success my-2 my-sm-0">Admin/Doctor Login</a>
                        <br /><br />
                    </form>
                    <form class="form-inline my-2 my-lg-0">


                        <a href="/User/Registration" class="btn btn-outline-success my-2 my-sm-0"><span class="glyphicon glyphicon-user"></span>Doctor Signup</a>
                    </form>
                </div>
            </nav>
    <div>
 

      
            <div class="row">
                <div class="col-md-2 ">
                    @if (ViewBag.RoleName == "Admin")
            {

                        @Html.Partial("AdminPartial")

            }
            else if (ViewBag.RoleName == "Doctor")
            {

                @Html.Partial("DoctorPartial")

            }
                </div>
                <div class="col-md-10 col-md-3" ">

                    @RenderBody()

                </div>
            </div>
    </div>
   
 
</body>
</html>

DoctorChamberAppointmentSystem/Views/Shared/_UserLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="~/Scripts/angular.min.js"></script>
    <script src="~/Scripts/AngularJsController/MyApp.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

</head>
<body ng-app="MyApp">


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"><img src="~/Image/logo.png" style="width:50%;" /></a>


        <div class=" navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">

                </li>
                <li class="nav-item">

                </li>
                <li class="nav-item">

                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">


                <a href="/User/Index" class="btn btn-outline-success my-2 my-sm-0">Admin/Doctor Login</a>
                <br /><br />
            </form>
            <form class="form-inline my-2 my-lg-0">


                <a href="/User/Registration" class="btn btn-outline-success my-2 my-sm-0"><span class="glyphicon glyphicon-user"></span>Doctor Signup</a>
            </form>
        </div>
    </nav>

    <div class="col-sm-3 col-md-3">
        @if (ViewBag.RoleName == "Admin")
        {

            @Html.Partial("AdminPartial")

        }
        else if (ViewBag.RoleName == "Doctor")
        {

            @Html.Partial("DoctorPartial")

        }
    </div>
    <div class="col-md-9">

        @RenderBody()

    </div>







</body>
</html>